# Generated by Django 3.2.18 on 2023-05-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('creator', models.CharField(max_length=20, verbose_name='Исполнитель')),
                ('file', models.FileField(null=True, upload_to='.main')),
            ],
        ),
        migrations.AddField(
            model_name='rock',
            name='photos',
            field=models.TextField(default='No photos', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='popular_songs',
            field=models.TextField(default='No popular songs', verbose_name='Топ 5 песен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='songs_mp3',
            field=models.TextField(default='NO songs', verbose_name='Песни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rock',
            name='time_life',
            field=models.CharField(max_length=15, verbose_name='Время существования'),
        ),
    ]
