# Generated by Django 3.2.18 on 2023-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230510_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': ''}, max_length=50, null=True, verbose_name='Название')),
                ('creator', models.CharField(error_messages={'required': ''}, max_length=20, null=True, verbose_name='Исполнитель')),
                ('file', models.FileField(error_messages={'required': ''}, null=True, upload_to='C:\\Users\\levto\\PycharmProjects\\site_for_grisha\\media')),
            ],
        ),
        migrations.DeleteModel(
            name='Covers',
        ),
    ]
