# Generated by Django 3.2.18 on 2023-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.ImageField(error_messages={'required': ''}, null=True, upload_to='C:\\Users\\levto\\PycharmProjects\\site_for_grisha\\media'),
        ),
    ]
