# Generated by Django 3.2.18 on 2023-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cover_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('rockers', models.TextField(verbose_name='Рокеры')),
                ('popular_songs', models.TextField(verbose_name='Топ 5 песен')),
                ('time_life', models.CharField(max_length=15, verbose_name='Время существования')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('songs_mp3', models.TextField(verbose_name='Песни')),
                ('photos', models.TextField(verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='rock',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='popular_songs',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='rockers',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='songs_mp3',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='time_life',
        ),
        migrations.AlterField(
            model_name='cover',
            name='creator',
            field=models.CharField(error_messages={'required': ''}, max_length=50, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.FileField(error_messages={'required': ''}, null=True, upload_to='C:\\Users\\levto\\PycharmProjects\\site_for_grisha\\media'),
        ),
        migrations.AlterField(
            model_name='rock',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
