# Generated by Django 3.2.18 on 2023-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230510_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='creator',
            field=models.CharField(blank=True, error_messages={'blank': '', 'null': '', 'required': ''}, max_length=50, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.FileField(blank=True, error_messages={'blank': '', 'null': '', 'required': ''}, null=True, upload_to='C:\\Users\\levto\\PycharmProjects\\site_for_grisha\\media', verbose_name='Кавер'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='title',
            field=models.CharField(blank=True, error_messages={'blank': '', 'null': '', 'required': ''}, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
