# Generated by Django 3.2.18 on 2023-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230510_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='title',
            field=models.CharField(error_messages={'blank': '', 'null': '', 'required': ''}, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
